### ISSUE TITLE
problems about running retouch_denoising

### ISSUE THREAD

**Issue by gala1a1** [lukas-gandler/OCT-Denoising#1]
Hi,
When I repeat the code and an error occurs, how do I correct it ?
“ValueError: invalid null reference in method 'ImageSeriesReader_SetFileNames', argument 2 of type 'std::vector< std::string,std::allocator< std::string > > const &'”（retouch_denoising.py）

**Comment by lukas-gandler** [comment]
Hi!

So far I have not been able to re-create your error. To me this looks like something went wrong when SimpleITK tried to read your input (although I am not an expert with this library).

This implementation targets the RETOUCH dataset which is organized as an `oct.mhd` and an accompanying `oct.raw` file. The file structure should then look like this:

    + your_OCT_scan/
    |-- oct.mhd
    |-- oct.raw
    +

To run this file, pass the `oct.mhd` and the number of denoising steps. 

One note here: This is just a demonstration on how this model could be used, therefore it only denoises slice in the middle of the volume as they show more complex and intersting structures. If you are interested in any other slice then you would have to slightly modify the code.

**Comment by gala1a1** [comment]
Thank you for your reply. I'll try again.
